name: Publish Stonebranch Extension

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Lint extension
        run: |
          python3 -m pip install --upgrade pip
          pip3 install flake8
          python3 -m flake8 --ignore=E501,E722
      - name: Build package
        run: |
          pip3 install --no-cache --upgrade pip setuptools twine
          VERSION=`python3 setup.py --version`
          python3 setup.py bdist_egg
          cp assets/* dist/
          cd dist/
          mv *.egg extension_archive.zip
          zip -r aws_stonebranch.zip extension_archive* template*
      - name: Archive extension artifacts
        uses: actions/upload-artifact@v3
        with:
          name: aws_mainframe_modernization_stonebranch_extension
          path: dist/aws_stonebranch.zip
